### PR TITLE
Add go.nut to related projects

### PR DESCRIPTION
**Pull request by robbiet480**
https://github.com/robbiet480/go.nut

### CODE REVIEW

**Comment by aquette** [comment]
hi @robbiet480 , thx for your contribution.
If you think this is stable, we may consider to distribute it part of NUT, under the scripts/go directory

**Comment by robbiet480** [comment]
@aquette I would want to add full tests first before doing that but I would be happy to have it distributed with NUT after that!

**Comment by aquette** [comment]
@robbiet480 : great! and I'm fully in favor of having tests for all things.
Please keep me updated.

**Comment by clepple** [comment]
@aquette I think this is definitely nice to have, and I do like the MIT license, but I really don't think we should mix GPL and MIT licensed code in the same repository. (Not all distros have Debian's flexibility on marking which licenses apply to a package.) We already split out jNut for other technical reasons, so having language bindings in separate repositories is not unprecedented.

**Comment by robbiet480** [comment]
@clepple @aquette Actually, I realized an even better reason to keep it out of scripts directory: Go won't like the code being in a subdirectory without a lot of hacks. 

I also agree that mixing licenses isn't always a great idea.

**Comment by robbiet480** [comment]
On another note, when will I see this change go live on either http://new.networkupstools.org/projects.html or http://networkupstools.org/projects.html? The readme made it sound like buildbot should automatically deploy it to `new.` but I don't see it. It won't go to networkupstools.org until the next full release though, correct? It works with protocol 1.2 so if it could go live before the next release (since it seems the release schedule is very spread out) that would be great but no rush :smile:

BTW, the reason I built the library is to add NUT support to [telegraf](https://github.com/influxdata/telegraf) so I can store UPS stats in InfluxDB for pretty display with Grafana. Hope to submit a PR to telegraf soon with my work.

**Comment by clepple** [comment]
@robbiet480 The reply-by-email thing seems to be broken (or maybe it doesn't work post-merge?), so to paraphrase: we do have to trigger the website rebuilds by hand at the moment, and they should end up at new.n.o. However, something else broke (maybe permissions?) and I am debugging that now.

If nothing else, we should probably update the news page between NUT releases.

Also, the protocol numbers shouldn't change often (ever again, IMHO - comparing version numbers is fragile) because old servers should respond with a well-defined `CMD-NOT-SUPPORTED` per the [protocol definition](http://networkupstools.org/docs/developer-guide.chunked/ar01s09.html#np-errors). Clients can try a new command to see if it is supported, and fall back if there is a less-efficient way to accomplish the same query.

**Comment by clepple** [comment]
>> On another note, when will I see this change go live on either http://new.networkupstools.org/projects.html <http://new.networkupstools.org/projects.html> or http://networkupstools.org/projects.html <http://networkupstools.org/projects.html>?
>> 
> It's not automatic yet

but it will go to new.networkupstools.org <http://new.networkupstools.org/> first.

I forget what we decided about when to update the rest of the site, given the news section. Maybe we can update that separately.

**Comment by clepple** [comment]
> On another note, when will I see this change go live on either http://new.networkupstools.org/projects.html <http://new.networkupstools.org/projects.html> or http://networkupstools.org/projects.html <http://networkupstools.org/projects.html>?
> 
It's not automatic yet. I kicked off a build this morning, and ran into some issues with the changes to support GitHub pages. The CI system doesn't need to be copying around all of the ancient Windows installers, for instance :-)
> The readme made it sound like buildbot should automatically deploy it to new. but I don't see it. It won't go to networkupstools.org until the next full release though, correct? It works with protocol 1.2 so if it could go live before the next release (since it seems the release schedule is very spread out) that would be great but no rush 😄
> 
The protocol really doesn't change that often, and one of my goals is to make sure that clients never need to know the exact version number. If a new feature gets implemented, new clients can try that first, and old servers will have a well-defined error response.

**Pull request merged**
